language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
deploy:
  script: "release"
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master